### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by evnmck** [ternjs/tern_for_vim#145] opened 2016-06-19 03:03 UTC
Hello,
I'm getting this error when i npm install in the .vim/bundle/tern_for_vim:
module.js:442
    throw err;
    ^

Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/tracker-stream.js:3:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

i installed vim with brew and installed macvim as well.  If you have any suggestions they would be much appreciated.

Thank you

**Comment by marijnh** [comment] 2016-06-20 08:50
This seems like an npm problem. Could it be that you have a somewhat old version of NPM installed? [This issue](https://github.com/npm/npm/issues/6366) seems related. In any case, I'm closing this, because it's definitely not caused by Tern.

**Closed by marijnh** 2016-06-20 08:50 UTC

**Comment by evnmck** [comment] 2016-06-21 05:07
Thank you! Yes I had some issues with node being installed both through brew and the node.js download.  Sorry for the trouble.

Evan
